name: Publish Docker
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ozeliurs-com:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/ozeliurs-com:latest
          cache-to: type=inline